version: '3.8'

services:
  mysql-master1:
    image: mysql:8.0
    container_name: mysql-master1
    # 若无data 和 conf 初次初始化可加
    # environment:
    #   MYSQL_ROOT_PASSWORD: rootpassword
    #   MYSQL_DATABASE: mydatabase
    #   MYSQL_USER: myuser
    #   MYSQL_PASSWORD: mypassword
    ports:
      - "13306:3306"
    volumes:
      - master1-data:/var/lib/mysql
      - master1-conf:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      shareJdbc:
        ipv4_address: 172.20.0.2

  mysql-master2:
    image: mysql:8.0
    container_name: mysql-master2
    # 若无data 和 conf 初次初始化可加
    # environment:
    #   MYSQL_ROOT_PASSWORD: rootpassword
    #   MYSQL_DATABASE: mydatabase
    #   MYSQL_USER: myuser
    #   MYSQL_PASSWORD: mypassword
    ports:
      - "13307:3306"
    volumes:
      - master2-data:/var/lib/mysql
      - master2-conf:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      shareJdbc:
        ipv4_address: 172.20.0.3

  mysql-slave1-1:
    image: mysql:8.0
    container_name: mysql-slave1-1
    # 若无data 和 conf 初次初始化可加
    # environment:
    #   MYSQL_ROOT_PASSWORD: rootpassword
    #   MYSQL_DATABASE: mydatabase
    #   MYSQL_USER: myuser
    #   MYSQL_PASSWORD: mypassword
    ports:
      - "13308:3306"
    volumes:
      - slave1-1-data:/var/lib/mysql
      - slave1-1-conf:/etc/mysql/conf.d
    depends_on:
      - mysql-master1
    command: --default-authentication-plugin=mysql_native_password
    networks:
      shareJdbc:
        ipv4_address: 172.20.0.4

  mysql-slave1-2:
    image: mysql:8.0
    container_name: mysql-slave1-2
    # 若无data 和 conf 初次初始化可加
    # environment:
    #   MYSQL_ROOT_PASSWORD: rootpassword
    #   MYSQL_DATABASE: mydatabase
    #   MYSQL_USER: myuser
    #   MYSQL_PASSWORD: mypassword
    ports:
      - "13309:3306"
    volumes:
      - slave1-2-data:/var/lib/mysql
      - slave1-2-conf:/etc/mysql/conf.d
    depends_on:
      - mysql-master1
    command: --default-authentication-plugin=mysql_native_password
    networks:
      shareJdbc:
        ipv4_address: 172.20.0.5

  mysql-slave2-1:
    image: mysql:8.0
    container_name: mysql-slave2-1
    # 若无data 和 conf 初次初始化可加
    # environment:
    #   MYSQL_ROOT_PASSWORD: rootpassword
    #   MYSQL_DATABASE: mydatabase
    #   MYSQL_USER: myuser
    #   MYSQL_PASSWORD: mypassword
    ports:
      - "13310:3306"
    volumes:
      - slave2-1-data:/var/lib/mysql
      - slave2-1-conf:/etc/mysql/conf.d
    depends_on:
      - mysql-master2
    command: --default-authentication-plugin=mysql_native_password
    networks:
      shareJdbc:
        ipv4_address: 172.20.0.6

  mysql-slave2-2:
    image: mysql:8.0
    container_name: mysql-slave2-2
    # 若无data 和 conf 初次初始化可加
    # environment:
    #   MYSQL_ROOT_PASSWORD: rootpassword
    #   MYSQL_DATABASE: mydatabase
    #   MYSQL_USER: myuser
    #   MYSQL_PASSWORD: mypassword
    ports:
      - "13311:3306"
    volumes:
      - slave2-2-data:/var/lib/mysql
      - slave2-2-conf:/etc/mysql/conf.d
    depends_on:
      - mysql-master2
    command: --default-authentication-plugin=mysql_native_password
    networks:
      shareJdbc:
        ipv4_address: 172.20.0.7

volumes:
  master1-data:
    driver: local
    driver_opts:
      type: none
      device: /volume2/docker/shareJdbc/master1/data
      o: bind
  master1-conf:
    driver: local
    driver_opts:
      type: none
      device: /volume2/docker/shareJdbc/master1/conf
      o: bind
  master2-data:
    driver: local
    driver_opts:
      type: none
      device: /volume2/docker/shareJdbc/master2/data
      o: bind
  master2-conf:
    driver: local
    driver_opts:
      type: none
      device: /volume2/docker/shareJdbc/master2/conf
      o: bind
  slave1-1-data:
    driver: local
    driver_opts:
      type: none
      device: /volume2/docker/shareJdbc/slave1-1/data
      o: bind
  slave1-1-conf:
    driver: local
    driver_opts:
      type: none
      device: /volume2/docker/shareJdbc/slave1-1/conf
      o: bind
  slave1-2-data:
    driver: local
    driver_opts:
      type: none
      device: /volume2/docker/shareJdbc/slave1-2/data
      o: bind
  slave1-2-conf:
    driver: local
    driver_opts:
      type: none
      device: /volume2/docker/shareJdbc/slave1-2/conf
      o: bind
  slave2-1-data:
    driver: local
    driver_opts:
      type: none
      device: /volume2/docker/shareJdbc/slave2-1/data
      o: bind
  slave2-1-conf:
    driver: local
    driver_opts:
      type: none
      device: /volume2/docker/shareJdbc/slave2-1/conf
      o: bind
  slave2-2-data:
    driver: local
    driver_opts:
      type: none
      device: /volume2/docker/shareJdbc/slave2-2/data
      o: bind
  slave2-2-conf:
    driver: local
    driver_opts:
      type: none
      device: /volume2/docker/shareJdbc/slave2-2/conf
      o: bind

networks:
  shareJdbc:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.0.0/20